---
apiVersion: v1
kind: Namespace
metadata:
  name: openpilot-installer
  labels:
    app: php-fpm-nginx

---
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: openpilot-installer
  name: nginx-config
data:
  nginx.conf: |
    events {
    }
    http {
      server {
        listen 80 default_server;
        listen [::]:80 default_server;
        add_header X-Frame-Options "SAMEORIGIN";
        add_header X-XSS-Protection "1; mode=block";
        add_header X-Content-Type-Options "nosniff";
        root /var/www/html/fork;
        index index.php;
        server_name _;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php/?.*$ {
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index index.php;
            fastcgi_split_path_info  ^((?U).+\.php)(/?.+)$;
            fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
            fastcgi_param  PATH_INFO  $fastcgi_path_info;
            fastcgi_param  PATH_TRANSLATED  $document_root$fastcgi_path_info;
            include fastcgi_params;
        }

        location = /favicon.ico { access_log off; log_not_found off; }
        location = /robots.txt  { access_log off; log_not_found off; }
      }
    }

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: openpilot-installer
  name: php-fpm-nginx
spec:
  selector:
    matchLabels:
      app: php-fpm-nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: php-fpm-nginx
    spec:
      containers:
        - name: php-fpm
          image: ccr.ccs.tencentyun.com/xspace/openpilot-installer:0.0.1.28.8c5ac6f
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
          volumeMounts:
            - mountPath: /var/www/html
              name: nginx-www
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "cp -r /app/. /var/www/html"]
            preStop:
              exec:
                command:
                  - sh
                  - '-c'
                  - sleep 5 && kill -SIGQUIT 1
        - name: nginx
          image: nginx:stable-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /var/www/html
              name: nginx-www
            - mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              name: nginx-config
          lifecycle:
            preStop:
              exec:
                command:
                  - sh
                  - '-c'
                  - sleep 5 && /usr/sbin/nginx -s quit
      volumes:
        - name: nginx-www
          emptyDir: {}
        - name: nginx-config
          configMap:
            name: nginx-config
---
kind: Service
apiVersion: v1
metadata:
  namespace: openpilot-installer
  name: php-fpm-nginx-svc
spec:
  selector:
    app: php-fpm-nginx
  #type: NodePort
  ports:
    - port: 80
      targetPort: 80
      #nodePort: 30080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: openpilot-installer
  name: php-fpm-nginx-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: openpilot.bgton.cn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: php-fpm-nginx-svc
                port:
                  number: 80